### ISSUE TITLE
Dockerfile best practice 

### ISSUE THREAD

**Issue by blakegao** [wacky6/hikaru#1]
1. Don't use multiple "RUN", should use "RUN" and "&&" instead. Because every "RUN" will add a new layer, just like an onion.

2. Maybe you also need to specify the node version of "alpine".

**Comment by blakegao** [comment]
快改😒，不改还偷偷close，哼！

**Comment by wacky6** [comment]
不改。

多个 RUN cache 提升测试愉快度。
版本永远跟最新版。不存在锁版本
